# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20170104_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=set([('quote_text', 'author')]),
        ),
    ]
